### ISSUE TITLE
Server Side Crash with hctm base

### ISSUE THREAD

**Issue by Mysticpasta1** [2xsaiko/hctm-base#7]
Latest Full Log
[latest (3).log](https://github.com/2xsaiko/hctm-base/files/6797037/latest.3.log)

Part of the Log I thought was important
[message (2).txt](https://github.com/2xsaiko/hctm-base/files/6797039/message.2.txt)

**Comment by dblsaiko** [comment]
Please check if [rswires 4.11.1](https://ci.dblsaiko.net/job/rswires/18/) fixes the issue.
